#!/usr/bin/env python3
"""
Automatically update README.md with commit changes descriptions generated by DeepSeek AI
"""

import os
import re
import requests
from datetime import datetime
from git import Repo, Diff
from typing import Dict, List, Optional
from dataclasses import dataclass
from pathlib import Path

# Configuration
DEEPSEEK_API_URL = "https://api.siliconflow.cn/v1/chat/completions"
README_PATH = "README.md"
MAX_DIFF_LENGTH = 4000  # To avoid hitting API limits
COMMIT_SKIP_PATTERNS = ["skip ci", "auto-update", "update readme"]

@dataclass
class FileChange:
    filename: str
    change_type: str  # 'added', 'modified', 'deleted', 'renamed'
    diff: str
    description: Optional[str] = None

class ReadmeUpdater:
    def __init__(self):
        self.repo = Repo('.')
        self.api_key = os.getenv('DEEPSEEK_API_KEY')
        if not self.api_key:
            raise ValueError("DEEPSEEK_API_KEY environment variable not set")

    def should_skip_commit(self, commit) -> bool:
        """Check if commit should be skipped"""
        if any(pattern in commit.message.lower() for pattern in COMMIT_SKIP_PATTERNS):
            return True
        return "actions" in commit.committer.email.lower()

    def get_changes(self, commit) -> List[FileChange]:
        """Get list of changed files with diffs"""
        changes = []
        
        if not commit.parents:  # Initial commit
            for item in commit.tree.traverse():
                if item.type == 'blob':  # Regular file
                    changes.append(FileChange(
                        filename=item.path,
                        change_type='added',
                        diff=f"Initial commit: {item.path}"
                    ))
            return changes

        parent = commit.parents[0]
        diffs = parent.diff(commit, create_patch=True)
        
        for diff in diffs:
            change_type = 'modified'
            if diff.new_file:
                change_type = 'added'
            elif diff.deleted_file:
                change_type = 'deleted'
            elif diff.renamed_file:
                change_type = 'renamed'

            diff_text = diff.diff.decode('utf-8', errors='replace')[:MAX_DIFF_LENGTH]
            changes.append(FileChange(
                filename=diff.b_path if diff.b_path else diff.a_path,
                change_type=change_type,
                diff=diff_text
            ))
        
        return changes

    def generate_change_description(self, diff: str) -> str:
        """Get AI-generated description of changes"""
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        prompt = f"""
        Analyze these code changes and provide a concise description in Russian.
        Focus on meaningful changes, skip trivial details.
        Use markdown bullet points.
        
        Changes:
        {diff}
        """
        
        data = {
            "model": "deepseek-chat",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.7,
            "max_tokens": 500
        }
        
        try:
            response = requests.post(DEEPSEEK_API_URL, headers=headers, json=data, timeout=30)
            response.raise_for_status()
            return response.json()['choices'][0]['message']['content'].strip()
        except Exception as e:
            print(f"Error getting AI description: {e}")
            return "Описание изменений недоступно"

    def format_change_entry(self, change: FileChange) -> str:
        """Format single file change entry for README"""
        prefix = {
            'added': '+',
            'modified': '*',
            'deleted': '-',
            'renamed': '→'
        }.get(change.change_type, '*')
        
        entry = f"----{prefix} {change.filename}\n       |\n"
        
        if not change.description:
            change.description = self.generate_change_description(change.diff)
        
        # Clean up and format the AI response
        lines = [line.strip() for line in change.description.split('\n') if line.strip()]
        for i, line in enumerate(lines, 1):
            # Remove existing bullet points if present
            line = re.sub(r'^[-\*•]\s*', '', line)
            entry += f"       -----{i}. {line}\n"
        
        return entry

    def update_readme(self):
        """Main function to update README with changes"""
        commit = self.repo.head.commit
        
        if self.should_skip_commit(commit):
            print("Skipping commit made by CI or with skip pattern")
            return
        
        commit_date = datetime.fromtimestamp(commit.committed_date).strftime('%d.%m.%Y')
        changes = self.get_changes(commit)
        
        if not changes:
            print("No file changes detected")
            return
        
        # Generate descriptions for all changes
        for change in changes:
            if change.change_type != 'deleted':  # Skip descriptions for deletions
                change.description = self.generate_change_description(change.diff)
        
        # Build the new entry
        new_entry = f"{commit_date}\n|\n"
        for change in changes:
            new_entry += self.format_change_entry(change)
        new_entry += "\n"
        
        # Update README
        readme_content = ""
        if Path(README_PATH).exists():
            with open(README_PATH, 'r', encoding='utf-8') as f:
                readme_content = f.read()
        
        # Insert new entry after header
        if "# История изменений" in readme_content:
            updated_content = readme_content.replace(
                "# История изменений\n",
                f"# История изменений\n\n{new_entry}"
            )
        else:
            updated_content = f"# История изменений\n\n{new_entry}\n{readme_content}"
        
        with open(README_PATH, 'w', encoding='utf-8') as f:
            f.write(updated_content)
        
        print("README updated successfully")

if __name__ == "__main__":
    try:
        updater = ReadmeUpdater()
        updater.update_readme()
    except Exception as e:
        print(f"Error updating README: {e}")
        exit(1)