name: CI Pipeline

on:
  push:
    branches: [main, develop]

jobs:
  check-stop:
    runs-on: ubuntu-latest
    steps:
      - name: Get BUILD_STOP_VALUE
        run: |
          ../GETDATA_API/getupdatedata_api.sh

  build:
    runs-on: ubuntu-latest
    needs: check-stop
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "🏗️ Build running..."
