name: CI Pipeline

on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          SV_TOKEN: ${{ secrets.SV_TOKEN }}
          REPO: ${{ github.repository }}
        run: | 
          REPO_FULL="${{ github.repository }}"
          echo "$REPO_FULL"
          echo "$REPO"
          #curl -X POST "https://events.statsigapi.net/v1/log_event" \
          #  -H "Content-Type: application/json" \
          #  -H "statsig-api-key: $STATSIG_API_KEY" \
          #  -d '{
          #    "events": [{
          #      "eventName": "github_issue_created",
          #      "metadata": {
          #        "issue_number": "'"$ISSUE_NUMBER"'",
          #        "repository": "'"$REPO"'",
          #        "title": "'"$(echo "$ISSUE_TITLE" | sed "s/\"/\\\\\"/g")"'",
          #        "author": "'"$AUTHOR"'",
          #        "created_at": "'"$CREATED_AT"'"
          #      },
          #      "time": '"$(date +%s)000"'
          #    }]
          #  }'
